import { User, UserRole, Product, Test, Bill, Due, Settings, Employee, SalaryPayment, DailyExpense, Party, PartyPayment } from '../types';

export const mockUsers: User[] = [
    { id: 'user-1', fullName: 'Center Admin', email: 'center@test.com', password: 'password', role: UserRole.CENTER },
    { id: 'user-2', fullName: 'Shop Owner', email: 'owner@test.com', password: 'password', role: UserRole.OWNER },
    { id: 'user-3', fullName: 'Jane Owner', email: 'owner2@test.com', password: 'password', role: UserRole.OWNER },
];

export const mockOwnerDevices: string[] = ['user-2']; // Pre-populate with one owner device

export const mockProducts: Product[] = [];

export const mockTests: Test[] = [
  { id: 'test-LDBIO0035', code: 'LDBIO0035', name: 'ADENOSINE DEAMINASE (ADA)', mrp: 750, department: 'Biochemistry' },
  { id: 'test-LDBIO0125', code: 'LDBIO0125', name: 'Alanine Amino-transferase (ALT) SGPT', mrp: 210, department: 'Biochemistry' },
  { id: 'test-LDBIO0138', code: 'LDBIO0138', name: 'AMYLASE, SERUM', mrp: 550, department: 'Biochemistry' },
  { id: 'test-LDBIO0147', code: 'LDBIO0147', name: 'ANGIOTENSIN CONVERTING ENZYME (ACE)', mrp: 600, department: 'Biochemistry' },
  { id: 'test-LDBIO0202', code: 'LDBIO0202', name: 'Aspartate Aminotransferase (AST) SGOT', mrp: 210, department: 'Biochemistry' },
  { id: 'test-LDBIO0240', code: 'LDBIO0240', name: 'BILIRUBIN TOTAL, DIRECT & INDIRECT', mrp: 300, department: 'Biochemistry' },
  { id: 'test-LDBIO0253', code: 'LDBIO0253', name: 'Blood Glucose Fasting (FBS)', mrp: 80, department: 'Biochemistry' },
  { id: 'test-LDBIO0255', code: 'LDBIO0255', name: 'Blood Glucose Post prandial (PPBS)', mrp: 80, department: 'Biochemistry' },
  { id: 'test-LDBIO0258', code: 'LDBIO0258', name: 'BLOOD UREA NITROGEN (BUN)', mrp: 230, department: 'Biochemistry' },
  { id: 'test-LDBIO0281', code: 'LDBIO0281', name: 'C3 Complement', mrp: 700, department: 'Biochemistry' },
  { id: 'test-LDBIO0282', code: 'LDBIO0282', name: 'C4 Complement', mrp: 650, department: 'Biochemistry' },
  { id: 'test-LDBIO0345', code: 'LDBIO0345', name: 'Ceruloplasmin, Serum', mrp: 1200, department: 'Biochemistry' },
  { id: 'test-LDBIO0360', code: 'LDBIO0360', name: 'Cholesterol Total', mrp: 250, department: 'Biochemistry' },
  { id: 'test-LDBIO0402', code: 'LDBIO0402', name: 'C-REACTIVE PROTEIN (CRP), ǪUANTITATIVE', mrp: 600, department: 'Biochemistry' },
  { id: 'test-LDBIO0403', code: 'LDBIO0403', name: 'Creatine Phosphokinase (CK/CPK), Serum', mrp: 500, department: 'Biochemistry' },
  { id: 'test-LDBIO0404', code: 'LDBIO0404', name: 'Creatine Phosphokinase MB (CPK-MB)', mrp: 470, department: 'Biochemistry' },
  { id: 'test-LDBIO0408', code: 'LDBIO0408', name: 'CREATININE, SERUM', mrp: 200, department: 'Biochemistry' },
  { id: 'test-LDBIO0497', code: 'LDBIO0497', name: 'Electrolytes, Serum', mrp: 550, department: 'Biochemistry' },
  { id: 'test-LDBIO0634', code: 'LDBIO0634', name: 'HBA1C (GLYCATED HAEMOGLOBIN)', mrp: 600, department: 'Biochemistry' },
  { id: 'test-LDBIO0882', code: 'LDBIO0882', name: 'IRON STUDIES, BASIC', mrp: 600, department: 'Biochemistry' },
  { id: 'test-LDBIO0885', code: 'LDBIO0885', name: 'Iron, Serum', mrp: 350, department: 'Biochemistry' },
  { id: 'test-LDBIO0904', code: 'LDBIO0904', name: 'KIDNEY/RENAL FUNCTION TESTS GOLD (KFT GOLD /RFT GOLD)', mrp: 1060, department: 'Biochemistry' },
  { id: 'test-LDBIO0929', code: 'LDBIO0929', name: 'LIPASE', mrp: 750, department: 'Biochemistry' },
  { id: 'test-LDBIO0936', code: 'LDBIO0936', name: 'Liver Function Test Gold (LFT Gold)', mrp: 900, department: 'Biochemistry' },
  { id: 'test-LDBIO0937', code: 'LDBIO0937', name: 'LUPUS ANTICOAGULANT (DRVVT)', mrp: 1700, department: 'Biochemistry' },
  { id: 'test-LDBIO1152', code: 'LDBIO1152', name: 'SERUM PROTEIN ELECTROPHORESIS (SPE)', mrp: 850, department: 'Biochemistry' },
  { id: 'test-LDBIO1207', code: 'LDBIO1207', name: 'Total Iron Binding Capacity (TIBC)', mrp: 650, department: 'Biochemistry' },
  { id: 'test-LDBIO1209', code: 'LDBIO1209', name: 'Total Protein , Serum', mrp: 190, department: 'Biochemistry' },
  { id: 'test-LDBIO1225', code: 'LDBIO1225', name: 'Triglycerides, Serum', mrp: 340, department: 'Biochemistry' },
  { id: 'test-LDBIO1229', code: 'LDBIO1229', name: 'Troponin - T', mrp: 1500, department: 'Biochemistry' },
  { id: 'test-LDBIO1247', code: 'LDBIO1247', name: 'URIC ACID, SERUM', mrp: 200, department: 'Biochemistry' },
  { id: 'test-LDBIO1573', code: 'LDBIO1573', name: 'Kappa Free Light Chain, Serum', mrp: 2600, department: 'Biochemistry' },
  { id: 'test-LDBIO1796', code: 'LDBIO1796', name: 'LIPID PROFILE', mrp: 750, department: 'Biochemistry' },
  { id: 'test-LDCOA1107', code: 'LDCOA1107', name: 'Prothombin Time (PT/INR)', mrp: 400, department: 'Coagulation' },
  { id: 'test-LDCYT0560', code: 'LDCYT0560', name: 'FLUID EXAMINATION, ROUTINE', mrp: 700, department: 'Cytology' },
  { id: 'test-LDCYT1046', code: 'LDCYT1046', name: 'PAP SMEAR BY LBC / LIǪUID BASED CYTOLOGY', mrp: 1300, department: 'Cytology' },
  { id: 'test-LDCYT1047', code: 'LDCYT1047', name: 'PAP SMEAR BY LBC WITH HPV HIGH RISK DETECTION', mrp: 2350, department: 'Cytology' },
  { id: 'test-LDFLO0334', code: 'LDFLO0334', name: 'CD4/CD8, FLOWCYTOMETRY', mrp: 2000, department: 'Flowcytometry' },
  { id: 'test-LDHEM0014', code: 'LDHEM0014', name: 'ABNORMAL HEMOGLOBIN STUDY (HB ELECTROPHORESIS)', mrp: 1000, department: 'Hematology' },
  { id: 'test-LDHEM0257', code: 'LDHEM0257', name: 'Blood Group ABO and Rh Typing', mrp: 120, department: 'Hematology' },
  { id: 'test-LDHEM0378', code: 'LDHEM0378', name: 'COMPLETE BLOOD COUNT (CBC)', mrp: 350, department: 'Hematology' },
  { id: 'test-LDHEM0379', code: 'LDHEM0379', name: 'Complete Urine Examination', mrp: 120, department: 'Hematology' },
  { id: 'test-LDHEM0382', code: 'LDHEM0382', name: 'Coombs Test, Direct', mrp: 550, department: 'Hematology' },
  { id: 'test-LDHEM0383', code: 'LDHEM0383', name: 'COOMBS TEST, INDIRECT', mrp: 550, department: 'Hematology' },
  { id: 'test-LDHEM0504', code: 'LDHEM0504', name: 'Erythrocyte Sedimentation Rate (ESR)', mrp: 120, department: 'Hematology' },
  { id: 'test-LDHEM0603', code: 'LDHEM0603', name: 'Glucose-6 Phosphate Dehydrogenase (G6PD), Ǫuantitative', mrp: 1050, department: 'Hematology' },
  { id: 'test-LDHEM0622', code: 'LDHEM0622', name: 'Hemoglobin (Hb)', mrp: 110, department: 'Hematology' },
  { id: 'test-LDHEM0626', code: 'LDHEM0626', name: 'HEMOGRAM (CBC WITH ESR)', mrp: 500, department: 'Hematology' },
  { id: 'test-LDHEM0948', code: 'LDHEM0948', name: 'Malaria Antigen Test', mrp: 650, department: 'Hematology' },
  { id: 'test-LDHEM1058', code: 'LDHEM1058', name: 'PERIPHERAL BLOOD SMEAR FOR MALARIAL PARASITE (PS FOR MP)', mrp: 180, department: 'Hematology' },
  { id: 'test-LDHEM1566', code: 'LDHEM1566', name: 'Platelet Count', mrp: 120, department: 'Hematology' },
  { id: 'test-LDHIS0680', code: 'LDHIS0680', name: 'HISTOPATHOLOGY- LARGE SPECIMEN', mrp: 1900, department: 'Histopathology' },
  { id: 'test-LDHIS0681', code: 'LDHIS0681', name: 'HISTOPATHOLOGY- MEDIUM SPECIMEN', mrp: 1300, department: 'Histopathology' },
  { id: 'test-LDHIS0691', code: 'LDHIS0691', name: 'HISTOPATHOLOGY- SMALL SPECIMEN', mrp: 800, department: 'Histopathology' },
  { id: 'test-LDIMM0120', code: 'LDIMM0120', name: 'ALPHA FETOPROTEIN (AFP), SERUM', mrp: 800, department: 'Immunology' },
  { id: 'test-LDIMM0152', code: 'LDIMM0152', name: 'ANTI - ds DNA , IFA in Dilutions', mrp: 3250, department: 'Immunology' },
  { id: 'test-LDIMM0169', code: 'LDIMM0169', name: 'ANTI MULLERIAN HORMONE (AMH), SERUM', mrp: 2200, department: 'Immunology' },
  { id: 'test-LDIMM0174', code: 'LDIMM0174', name: 'Anti Phospholipid Antibodies IgG & IgM', mrp: 1450, department: 'Immunology' },
  { id: 'test-LDIMM0231', code: 'LDIMM0231', name: 'BETA HCG, SERUM', mrp: 800, department: 'Immunology' },
  { id: 'test-LDIMM0277', code: 'LDIMM0277', name: 'C -PEPTIDE (FASTING)', mrp: 1100, department: 'Immunology' },
  { id: 'test-LDIMM0285', code: 'LDIMM0285', name: 'CA 19-9', mrp: 1100, department: 'Immunology' },
  { id: 'test-LDIMM0286', code: 'LDIMM0286', name: 'CA 72-4 (Gastric Cancer)', mrp: 1900, department: 'Immunology' },
  { id: 'test-LDIMM0287', code: 'LDIMM0287', name: 'CA 125', mrp: 1400, department: 'Immunology' },
  { id: 'test-LDIMM0288', code: 'LDIMM0288', name: 'CA 15-3', mrp: 1250, department: 'Immunology' },
  { id: 'test-LDIMM0292', code: 'LDIMM0292', name: 'Calcium', mrp: 210, department: 'Immunology' },
  { id: 'test-LDIMM0305', code: 'LDIMM0305', name: 'CARCINO EMBYONIC ANTIGEN (CEA), SERUM', mrp: 720, department: 'Immunology' },
  { id: 'test-LDIMM0390', code: 'LDIMM0390', name: 'CORTISOL (MORNING SAMPLE)', mrp: 700, department: 'Immunology' },
  { id: 'test-LDIMM0481', code: 'LDIMM0481', name: 'DUAL MARKER (DOUBLE MARKER)- FIRST TRIMESTER', mrp: 2400, department: 'Immunology' },
  { id: 'test-LDIMM0484', code: 'LDIMM0484', name: 'E2 (ESTRADIOL)', mrp: 700, department: 'Immunology' },
  { id: 'test-LDIMM0528', code: 'LDIMM0528', name: 'FERRITIN', mrp: 800, department: 'Immunology' },
  { id: 'test-LDIMM0568', code: 'LDIMM0568', name: 'FOLATE/FOLIC ACID, SERUM', mrp: 1100, department: 'Immunology' },
  { id: 'test-LDIMM0569', code: 'LDIMM0569', name: 'FOLLICLE STIMULATING HORMONE (FSH)', mrp: 650, department: 'Immunology' },
  { id: 'test-LDIMM0723', code: 'LDIMM0723', name: 'HOMA IR (insulin resistance)', mrp: 1000, department: 'Immunology' },
  { id: 'test-LDIMM0863', code: 'LDIMM0863', name: 'IMMUNOGLOBULIN IGE (TOTAL IGE)', mrp: 900, department: 'Immunology' },
  { id: 'test-LDIMM0874', code: 'LDIMM0874', name: 'INSULIN (FASTING)', mrp: 850, department: 'Immunology' },
  { id: 'test-LDIMM0879', code: 'LDIMM0879', name: 'INSULIN PP', mrp: 850, department: 'Immunology' },
  { id: 'test-LDIMM0938', code: 'LDIMM0938', name: 'LUTEINIZING HORMONE (LH)', mrp: 600, department: 'Immunology' },
  { id: 'test-LDIMM0963', code: 'LDIMM0963', name: 'Microalbumin Creatinine Ratio, Spot Urine', mrp: 700, department: 'Immunology' },
  { id: 'test-LDIMM1025', code: 'LDIMM1025', name: 'NT-pro BNP', mrp: 3800, department: 'Immunology' },
  { id: 'test-LDIMM1092', code: 'LDIMM1092', name: 'PROGESTERONE', mrp: 700, department: 'Immunology' },
  { id: 'test-LDIMM1094', code: 'LDIMM1094', name: 'PROLACTIN', mrp: 650, department: 'Immunology' },
  { id: 'test-LDIMM1096', code: 'LDIMM1096', name: 'PROSTATE SPECIFIC ANTIGEN, FREE (FREE PSA)', mrp: 850, department: 'Immunology' },
  { id: 'test-LDIMM1097', code: 'LDIMM1097', name: 'PROSTATE SPECIFIC ANTIGEN, TOTAL (TOTAL PSA)', mrp: 950, department: 'Immunology' },
  { id: 'test-LDIMM1110', code: 'LDIMM1110', name: 'PTH (INTACT)-PARATHYROID HORMONE', mrp: 1600, department: 'Immunology' },
  { id: 'test-LDIMM1112', code: 'LDIMM1112', name: 'ǪUADRUPLE MARKER- SECOND TRIMESTER', mrp: 3500, department: 'Immunology' },
  { id: 'test-LDIMM1186', code: 'LDIMM1186', name: 'TESTOSTERONE TOTAL', mrp: 800, department: 'Immunology' },
  { id: 'test-LDIMM1191', code: 'LDIMM1191', name: 'THYROID PROFILE FREE', mrp: 1200, department: 'Immunology' },
  { id: 'test-LDIMM1192', code: 'LDIMM1192', name: 'THYROID PROFILE TOTAL', mrp: 660, department: 'Immunology' },
  { id: 'test-LDIMM1195', code: 'LDIMM1195', name: 'THYROID STIMULATING HORMONE (TSH), ULTRASENSITIVE', mrp: 350, department: 'Immunology' },
  { id: 'test-LDIMM1212', code: 'LDIMM1212', name: 'Toxoplasma Antibodies panel', mrp: 1000, department: 'Immunology' },
  { id: 'test-LDIMM1227', code: 'LDIMM1227', name: 'TRIPLE MARKER- SECOND TRIMESTER', mrp: 2900, department: 'Immunology' },
  { id: 'test-LDIMM1268', code: 'LDIMM1268', name: 'VITAMIN B12 (CYANOCOBALAMIN)', mrp: 1210, department: 'Immunology' },
  { id: 'test-LDIMM1274', code: 'LDIMM1274', name: 'VITAMIN D, 25 - OH', mrp: 1500, department: 'Immunology' },
  { id: 'test-LDIMM1314', code: 'LDIMM1314', name: 'Dengue Fever Antibodies ( IgG, IgM) ELISA', mrp: 1870, department: 'Immunology' },
  { id: 'test-LDIMM1320', code: 'LDIMM1320', name: 'FSH/LH/PROLACTIN', mrp: 1800, department: 'Immunology' },
  { id: 'test-LDIMM1321', code: 'LDIMM1321', name: 'FT4 & TSH', mrp: 650, department: 'Immunology' },
  { id: 'test-LDIMM1638', code: 'LDIMM1638', name: 'ANC PROFILE WITH TSH', mrp: 1750, department: 'Immunology' },
  { id: 'test-LDIMU0072', code: 'LDIMU0072', name: 'AMH GOLD PLUS', mrp: 2500, department: 'Immunology' },
  { id: 'test-LDLKP1592', code: 'LDLKP1592', name: 'Troponin I- Ǫualitative', mrp: 1900, department: 'Lab' },
  { id: 'test-LDMIC0040', code: 'LDMIC0040', name: 'AFB smear (Acid fast bacilli)', mrp: 300, department: 'Microbiology' },
  { id: 'test-LDMIC0417', code: 'LDMIC0417', name: 'CULTURE AND SENSITIVITY, AEROBIC- VITEK', mrp: 750, department: 'Microbiology' },
  { id: 'test-LDMIC0419', code: 'LDMIC0419', name: 'CULTURE AUTOMATED BLOOD AEROBIC- VITEK', mrp: 1500, department: 'Microbiology' },
  { id: 'test-LDMIC0424', code: 'LDMIC0424', name: 'CULTURE MTB, AUTOMATED', mrp: 950, department: 'Microbiology' },
  { id: 'test-LDMIC1327', code: 'LDMIC1327', name: 'STOOL CULTURE AND SENSITIVITY', mrp: 750, department: 'Microbiology' },
  { id: 'test-LDMIC1328', code: 'LDMIC1328', name: 'CULTURE AND SENSITIVITY, URINE- VITEK', mrp: 750, department: 'Microbiology' },
  { id: 'test-LDMICRO2028', code: 'LDMICRO2028', name: 'Urine Culture & Sensitivity', mrp: 500, department: 'Microbiology' },
  { id: 'test-LDMOL0594', code: 'LDMOL0594', name: 'GENEXPERT MTB/RIF', mrp: 2800, department: 'Molecular' },
  { id: 'test-LDMOL0637', code: 'LDMOL0637', name: 'HBV DNA PCR Ǫuantitative, Real Time PCR', mrp: 5000, department: 'Molecular' },
  { id: 'test-LDMOL0641', code: 'LDMOL0641', name: 'Hepatitis C (HCV) Viral RNA Genotype', mrp: 6800, department: 'Molecular' },
  { id: 'test-LDMOL0645', code: 'LDMOL0645', name: 'HCV RNA PCR Ǫuantitative, Real Time PCR', mrp: 6000, department: 'Molecular' },
  { id: 'test-LDMOL0719', code: 'LDMOL0719', name: 'HLA B-27 by PCR', mrp: 2700, department: 'Molecular' },
  { id: 'test-LDMOL0895', code: 'LDMOL0895', name: 'KARYOTYPING BY G BANDING', mrp: 3000, department: 'Molecular' },
  { id: 'test-LDMOL1020', code: 'LDMOL1020', name: 'NON-INVASIVE PRENATAL TEST (NIPT)', mrp: 9990, department: 'Molecular' },
  { id: 'test-LDMOL1183', code: 'LDMOL1183', name: 'TB DNA PCR, ǪUALITATIVE', mrp: 1980, department: 'Molecular' },
  { id: 'test-LDMOL1466', code: 'LDMOL1466', name: 'H3 VIRAL MARKER PROFILE HIV, HBSAG,HCV', mrp: 1180, department: 'Molecular' },
  { id: 'test-LDSER0141', code: 'LDSER0141', name: 'ANA BY IMMUNOBLOT', mrp: 3300, department: 'Serology' },
  { id: 'test-LDSER0142', code: 'LDSER0142', name: 'ANA IFA reflex to ANA Immunoblot', mrp: 2800, department: 'Serology' },
  { id: 'test-LDSER0143', code: 'LDSER0143', name: 'ANA IFA, IN DILUTIONS', mrp: 1000, department: 'Serology' },
  { id: 'test-LDSER0145', code: 'LDSER0145', name: 'ANCA Profile, ELISA', mrp: 2000, department: 'Serology' },
  { id: 'test-LDSER0149', code: 'LDSER0149', name: 'HIV 1 & 2 ANTIBODIES, RAPID', mrp: 610, department: 'Serology' },
  { id: 'test-LDSER0154', code: 'LDSER0154', name: 'ANTI CYCLIC CITRULLINATED PEPTIDE (CCP)', mrp: 2000, department: 'Serology' },
  { id: 'test-LDSER0172', code: 'LDSER0172', name: 'Anti Phospholipid Antibodies (APA), IgG', mrp: 900, department: 'Serology' },
  { id: 'test-LDSER0173', code: 'LDSER0173', name: 'Anti Phospholipid Antibodies (APA), IgM', mrp: 900, department: 'Serology' },
  { id: 'test-LDSER0185', code: 'LDSER0185', name: 'Anti Streptolysin-O (ASO) Ǫuantitative', mrp: 620, department: 'Serology' },
  { id: 'test-LDSER0188', code: 'LDSER0188', name: 'ANTI TPO (THYROID PEROXIDASE) ANTIBODY)', mrp: 1500, department: 'Serology' },
  { id: 'test-LDSER0306', code: 'LDSER0306', name: 'Cardiolipin Antibodies IgG, IgM', mrp: 1500, department: 'Serology' },
  { id: 'test-LDSER0464', code: 'LDSER0464', name: 'Dengue NS1 Antigen, Rapid', mrp: 750, department: 'Serology' },
  { id: 'test-LDSER0521', code: 'LDSER0521', name: 'FAECAL CALPROTECTIN', mrp: 3200, department: 'Serology' },
  { id: 'test-LDSER0618', code: 'LDSER0618', name: 'H. Pylori Antibody IgG', mrp: 2000, department: 'Serology' },
  { id: 'test-LDSER0619', code: 'LDSER0619', name: 'H. Pylori Antibody IgM', mrp: 2500, department: 'Serology' },
  { id: 'test-LDSER0652', code: 'LDSER0652', name: 'HEPATITIS A VIRUS IGM ANTIBODY (HAV IGM)', mrp: 1100, department: 'Serology' },
  { id: 'test-LDSER0653', code: 'LDSER0653', name: 'Hepatitis A Virus Total Antibody (HAV Total)', mrp: 1300, department: 'Serology' },
  { id: 'test-LDSER0656', code: 'LDSER0656', name: 'HEPATITIS B SURFACE ANTIGEN (HBSAG), CLIA/ELISA', mrp: 1400, department: 'Serology' },
  { id: 'test-LDSER0657', code: 'LDSER0657', name: 'HEPATITIS B SURFACE ANTIGEN (HBSAG), RAPID METHOD', mrp: 580, department: 'Serology' },
  { id: 'test-LDSER0663', code: 'LDSER0663', name: 'Hepatitis B Virus core Total Antibody (HBc Total)', mrp: 1100, department: 'Serology' },
  { id: 'test-LDSER0665', code: 'LDSER0665', name: 'Hepatitis B Virus envelope Antigen (HBeAg)', mrp: 900, department: 'Serology' },
  { id: 'test-LDSER0668', code: 'LDSER0668', name: 'HEPATITIS C ANTIBODIES (HCV), RAPID', mrp: 500, department: 'Serology' },
  { id: 'test-LDSER0671', code: 'LDSER0671', name: 'Hepatitis E Virus IgG Antibody (HEV IgG)', mrp: 1500, department: 'Serology' },
  { id: 'test-LDSER0672', code: 'LDSER0672', name: 'HEPATITIS E VIRUS IGM ANTIBODY (HEV IGM)', mrp: 1500, department: 'Serology' },
  { id: 'test-LDSER1113', code: 'LDSER1113', name: 'ǪUANTIFERON TB GOLD/INTERFERON GAMMA RELEASE ASSAY (IGRA)', mrp: 3000, department: 'Serology' },
  { id: 'test-LDSER1122', code: 'LDSER1122', name: 'RHEUMATOID FACTOR(RA)', mrp: 650, department: 'Serology' },
  { id: 'test-LDSER1196', code: 'LDSER1196', name: 'Tissue Transglutaminase (tTG) IgA Antibody', mrp: 1300, department: 'Serology' },
  { id: 'test-LDSER1201', code: 'LDSER1201', name: 'TORCH 10 PROFILE', mrp: 3200, department: 'Serology' },
  { id: 'test-LDSER1234', code: 'LDSER1234', name: 'Typhidot IgM', mrp: 550, department: 'Serology' },
  { id: 'test-LDSER1262', code: 'LDSER1262', name: 'VDRL (RPR), Serum', mrp: 300, department: 'Serology' },
  { id: 'test-LDSER1288', code: 'LDSER1288', name: 'WIDAL (SLIDE AGGLUTINATION)', mrp: 250, department: 'Serology' },
  { id: 'test-LDSER1322', code: 'LDSER1322', name: 'Hb, TLC, DLC, Platelets', mrp: 300, department: 'Serology' },
  { id: 'test-LDSER1730', code: 'LDSER1730', name: 'Typhidot , Salmonella IgG', mrp: 480, department: 'Serology' },
  { id: 'test-LDSER1810', code: 'LDSER1810', name: 'H3 Viral marker profile HIV, HbsAg,HCV, Rapid', mrp: 1000, department: 'Serology' },
  { id: 'test-LDMOL0216', code: 'LDMOL0216', name: 'BCR/ABL Ǫuantitative (International Scale)', mrp: 6500, department: 'Molecular' },
  { id: 'test-LDIHC1674', code: 'LDIHC1674', name: 'IHC marker- ER, PgR, Her2neu', mrp: 3600, department: 'IHC' },

  // X-Ray Tests
  // 1) Skull & Brain X-Ray
  { id: 'test-XSK01', code: 'XSK01', name: 'X-Ray Skull AP', mrp: 400, department: 'Skull & Brain X-Ray' },
  { id: 'test-XSK02', code: 'XSK02', name: 'X-Ray Skull LAT', mrp: 400, department: 'Skull & Brain X-Ray' },
  { id: 'test-XSK03', code: 'XSK03', name: 'X-Ray Skull PA', mrp: 400, department: 'Skull & Brain X-Ray' },
  { id: 'test-XSK04', code: 'XSK04', name: 'X-Ray Skull both oblique', mrp: 800, department: 'Skull & Brain X-Ray' },
  { id: 'test-XSK05', code: 'XSK05', name: 'X-Ray Skull base view', mrp: 400, department: 'Skull & Brain X-Ray' },
  { id: 'test-XSK06', code: 'XSK06', name: 'X-Ray Sella Turcica', mrp: 400, department: 'Skull & Brain X-Ray' },
  { id: 'test-XSK07', code: 'XSK07', name: 'X-Ray Orbit AP', mrp: 400, department: 'Skull & Brain X-Ray' },
  { id: 'test-XSK08', code: 'XSK08', name: 'X-Ray Orbit LAT', mrp: 400, department: 'Skull & Brain X-Ray' },
  { id: 'test-XSK09', code: 'XSK09', name: 'X-Ray PNS (Paranasal Sinus)', mrp: 400, department: 'Skull & Brain X-Ray' },
  { id: 'test-XSK10', code: 'XSK10', name: 'X-Ray PNS Waters view', mrp: 400, department: 'Skull & Brain X-Ray' },
  { id: 'test-XSK11', code: 'XSK11', name: 'X-Ray TM Joint AP', mrp: 400, department: 'Skull & Brain X-Ray' },
  { id: 'test-XSK12', code: 'XSK12', name: 'X-Ray TM Joint LAT', mrp: 400, department: 'Skull & Brain X-Ray' },
  { id: 'test-XSK13', code: 'XSK13', name: 'X-Ray Mastoid AP', mrp: 400, department: 'Skull & Brain X-Ray' },
  { id: 'test-XSK14', code: 'XSK14', name: 'X-Ray Mastoid LAT', mrp: 400, department: 'Skull & Brain X-Ray' },
  { id: 'test-XSK15', code: 'XSK15', name: 'X-Ray Zygomatic arch', mrp: 400, department: 'Skull & Brain X-Ray' },
  { id: 'test-XSK16', code: 'XSK16', name: 'X-Ray Nasal bone LAT', mrp: 400, department: 'Skull & Brain X-Ray' },
  { id: 'test-XSK17', code: 'XSK17', name: 'X-Ray Nasal bone both LAT', mrp: 800, department: 'Skull & Brain X-Ray' },
  { id: 'test-XSK18', code: 'XSK18', name: 'X-Ray Occipital bone view', mrp: 400, department: 'Skull & Brain X-Ray' },
  // 2) Cervical Spine X-Ray
  { id: 'test-XCS01', code: 'XCS01', name: 'X-Ray C-Spine AP', mrp: 400, department: 'Cervical Spine X-Ray' },
  { id: 'test-XCS02', code: 'XCS02', name: 'X-Ray C-Spine LAT', mrp: 400, department: 'Cervical Spine X-Ray' },
  { id: 'test-XCS03', code: 'XCS03', name: 'X-Ray C-Spine Oblique (both sides)', mrp: 800, department: 'Cervical Spine X-Ray' },
  { id: 'test-XCS04', code: 'XCS04', name: 'X-Ray C-Spine Flexion', mrp: 400, department: 'Cervical Spine X-Ray' },
  { id: 'test-XCS05', code: 'XCS05', name: 'X-Ray C-Spine Extension', mrp: 400, department: 'Cervical Spine X-Ray' },
  { id: 'test-XCS06', code: 'XCS06', name: 'X-Ray Odontoid peg view (C1-C2)', mrp: 400, department: 'Cervical Spine X-Ray' },
  { id: 'test-XCS07', code: 'XCS07', name: 'X-Ray Atlanto-axial joint view', mrp: 400, department: 'Cervical Spine X-Ray' },
  // 3) Thoracic Spine X-Ray
  { id: 'test-XTS01', code: 'XTS01', name: 'X-Ray Dorsal/Thoracic Spine AP', mrp: 400, department: 'Thoracic Spine X-Ray' },
  { id: 'test-XTS02', code: 'XTS02', name: 'X-Ray Dorsal/Thoracic Spine LAT', mrp: 400, department: 'Thoracic Spine X-Ray' },
  { id: 'test-XTS03', code: 'XTS03', name: 'X-Ray Thoracic Oblique', mrp: 400, department: 'Thoracic Spine X-Ray' },
  // 4) Lumbar Spine X-Ray
  { id: 'test-XLS01', code: 'XLS01', name: 'X-Ray L-Spine AP', mrp: 400, department: 'Lumbar Spine X-Ray' },
  { id: 'test-XLS02', code: 'XLS02', name: 'X-Ray L-Spine LAT', mrp: 400, department: 'Lumbar Spine X-Ray' },
  { id: 'test-XLS03', code: 'XLS03', name: 'X-Ray L-Spine Oblique (both sides)', mrp: 800, department: 'Lumbar Spine X-Ray' },
  { id: 'test-XLS04', code: 'XLS04', name: 'X-Ray L-Spine Flexion view', mrp: 400, department: 'Lumbar Spine X-Ray' },
  { id: 'test-XLS05', code: 'XLS05', name: 'X-Ray L-Spine Extension view', mrp: 400, department: 'Lumbar Spine X-Ray' },
  { id: 'test-XLS06', code: 'XLS06', name: 'X-Ray Sacro-iliac Joint AP', mrp: 400, department: 'Lumbar Spine X-Ray' },
  { id: 'test-XLS07', code: 'XLS07', name: 'X-Ray Sacro-iliac Joint Oblique', mrp: 400, department: 'Lumbar Spine X-Ray' },
  // 5) Pelvis & Hip X-Ray
  { id: 'test-XPH01', code: 'XPH01', name: 'X-Ray Pelvis AP', mrp: 400, department: 'Pelvis & Hip X-Ray' },
  { id: 'test-XPH02', code: 'XPH02', name: 'X-Ray Pelvis LAT', mrp: 400, department: 'Pelvis & Hip X-Ray' },
  { id: 'test-XPH03', code: 'XPH03', name: 'X-Ray Hip Joint AP', mrp: 400, department: 'Pelvis & Hip X-Ray' },
  { id: 'test-XPH04', code: 'XPH04', name: 'X-Ray Hip Joint LAT', mrp: 400, department: 'Pelvis & Hip X-Ray' },
  { id: 'test-XPH05', code: 'XPH05', name: 'X-Ray Both Hip AP', mrp: 600, department: 'Pelvis & Hip X-Ray' },
  { id: 'test-XPH06', code: 'XPH06', name: 'X-Ray Both Hip LAT', mrp: 600, department: 'Pelvis & Hip X-Ray' },
  { id: 'test-XPH07', code: 'XPH07', name: 'X-Ray Acetabulum view', mrp: 400, department: 'Pelvis & Hip X-Ray' },
  { id: 'test-XPH08', code: 'XPH08', name: 'X-Ray Sacrum & Coccyx AP', mrp: 400, department: 'Pelvis & Hip X-Ray' },
  { id: 'test-XPH09', code: 'XPH09', name: 'X-Ray Sacrum & Coccyx LAT', mrp: 400, department: 'Pelvis & Hip X-Ray' },
  // 6) Chest X-Ray
  { id: 'test-XCH01', code: 'XCH01', name: 'X-Ray Chest PA', mrp: 400, department: 'Chest X-Ray' },
  { id: 'test-XCH02', code: 'XCH02', name: 'X-Ray Chest AP', mrp: 400, department: 'Chest X-Ray' },
  { id: 'test-XCH03', code: 'XCH03', name: 'X-Ray Chest LAT', mrp: 400, department: 'Chest X-Ray' },
  { id: 'test-XCH04', code: 'XCH04', name: 'X-Ray Chest Oblique', mrp: 400, department: 'Chest X-Ray' },
  { id: 'test-XCH05', code: 'XCH05', name: 'X-Ray Decubitus view', mrp: 400, department: 'Chest X-Ray' },
  { id: 'test-XCH06', code: 'XCH06', name: 'X-Ray Expiratory view', mrp: 400, department: 'Chest X-Ray' },
  { id: 'test-XCH07', code: 'XCH07', name: 'X-Ray Rib X-Ray (single/both)', mrp: 800, department: 'Chest X-Ray' },
  { id: 'test-XCH08', code: 'XCH08', name: 'X-Ray Clavicle AP', mrp: 400, department: 'Chest X-Ray' },
  { id: 'test-XCH09', code: 'XCH09', name: 'X-Ray Clavicle LAT', mrp: 400, department: 'Chest X-Ray' },
  // 7) Abdomen X-Ray
  { id: 'test-XAB01', code: 'XAB01', name: 'X-Ray Abdomen AP', mrp: 400, department: 'Abdomen X-Ray' },
  { id: 'test-XAB02', code: 'XAB02', name: 'X-Ray Abdomen erect', mrp: 400, department: 'Abdomen X-Ray' },
  { id: 'test-XAB03', code: 'XAB03', name: 'X-Ray KUB (Kidney-Ureter-Bladder)', mrp: 400, department: 'Abdomen X-Ray' },
  { id: 'test-XAB04', code: 'XAB04', name: 'X-Ray IVP preparation film', mrp: 400, department: 'Abdomen X-Ray' },
  { id: 'test-XAB05', code: 'XAB05', name: 'X-Ray Bowel obstruction views', mrp: 800, department: 'Abdomen X-Ray' },
  { id: 'test-XAB06', code: 'XAB06', name: 'X-Ray Abdomen LAT decubitus', mrp: 400, department: 'Abdomen X-Ray' },
  // 8) Upper Limb X-Ray
  { id: 'test-XUL01', code: 'XUL01', name: 'X-Ray Shoulder AP', mrp: 400, department: 'Upper Limb X-Ray' },
  { id: 'test-XUL02', code: 'XUL02', name: 'X-Ray Shoulder LAT (Y-view)', mrp: 400, department: 'Upper Limb X-Ray' },
  { id: 'test-XUL03', code: 'XUL03', name: 'X-Ray Shoulder Axial', mrp: 400, department: 'Upper Limb X-Ray' },
  { id: 'test-XUL04', code: 'XUL04', name: 'X-Ray Scapula AP', mrp: 400, department: 'Upper Limb X-Ray' },
  { id: 'test-XUL05', code: 'XUL05', name: 'X-Ray Scapula LAT', mrp: 400, department: 'Upper Limb X-Ray' },
  { id: 'test-XUL06', code: 'XUL06', name: 'X-Ray Humerus AP', mrp: 400, department: 'Upper Limb X-Ray' },
  { id: 'test-XUL07', code: 'XUL07', name: 'X-Ray Humerus LAT', mrp: 400, department: 'Upper Limb X-Ray' },
  { id: 'test-XUL08', code: 'XUL08', name: 'X-Ray Elbow AP', mrp: 400, department: 'Upper Limb X-Ray' },
  { id: 'test-XUL09', code: 'XUL09', name: 'X-Ray Elbow LAT', mrp: 400, department: 'Upper Limb X-Ray' },
  { id: 'test-XUL10', code: 'XUL10', name: 'X-Ray Elbow oblique', mrp: 400, department: 'Upper Limb X-Ray' },
  { id: 'test-XUL11', code: 'XUL11', name: 'X-Ray Forearm AP', mrp: 400, department: 'Upper Limb X-Ray' },
  { id: 'test-XUL12', code: 'XUL12', name: 'X-Ray Forearm LAT', mrp: 400, department: 'Upper Limb X-Ray' },
  { id: 'test-XUL13', code: 'XUL13', name: 'X-Ray Wrist AP', mrp: 400, department: 'Upper Limb X-Ray' },
  { id: 'test-XUL14', code: 'XUL14', name: 'X-Ray Wrist LAT', mrp: 400, department: 'Upper Limb X-Ray' },
  { id: 'test-XUL15', code: 'XUL15', name: 'X-Ray Wrist Oblique', mrp: 400, department: 'Upper Limb X-Ray' },
  { id: 'test-XUL16', code: 'XUL16', name: 'X-Ray Hand AP', mrp: 400, department: 'Upper Limb X-Ray' },
  { id: 'test-XUL17', code: 'XUL17', name: 'X-Ray Hand LAT', mrp: 400, department: 'Upper Limb X-Ray' },
  { id: 'test-XUL18', code: 'XUL18', name: 'X-Ray Hand Oblique', mrp: 400, department: 'Upper Limb X-Ray' },
  { id: 'test-XUL19', code: 'XUL19', name: 'X-Ray Fingers AP', mrp: 400, department: 'Upper Limb X-Ray' },
  { id: 'test-XUL20', code: 'XUL20', name: 'X-Ray Fingers LAT', mrp: 400, department: 'Upper Limb X-Ray' },
  { id: 'test-XUL21', code: 'XUL21', name: 'X-Ray Thumb AP', mrp: 400, department: 'Upper Limb X-Ray' },
  { id: 'test-XUL22', code: 'XUL22', name: 'X-Ray Thumb LAT', mrp: 400, department: 'Upper Limb X-Ray' },
  // 9) Lower Limb X-Ray
  { id: 'test-XLL01', code: 'XLL01', name: 'X-Ray Femur AP', mrp: 400, department: 'Lower Limb X-Ray' },
  { id: 'test-XLL02', code: 'XLL02', name: 'X-Ray Femur LAT', mrp: 400, department: 'Lower Limb X-Ray' },
  { id: 'test-XLL03', code: 'XLL03', name: 'X-Ray Knee AP', mrp: 400, department: 'Lower Limb X-Ray' },
  { id: 'test-XLL04', code: 'XLL04', name: 'X-Ray Knee LAT', mrp: 400, department: 'Lower Limb X-Ray' },
  { id: 'test-XLL05', code: 'XLL05', name: 'X-Ray Knee skyline patella', mrp: 400, department: 'Lower Limb X-Ray' },
  { id: 'test-XLL06', code: 'XLL06', name: 'X-Ray Bilateral knee AP/standing', mrp: 600, department: 'Lower Limb X-Ray' },
  { id: 'test-XLL07', code: 'XLL07', name: 'X-Ray Knee oblique', mrp: 400, department: 'Lower Limb X-Ray' },
  { id: 'test-XLL08', code: 'XLL08', name: 'X-Ray Tibia/Fibula AP', mrp: 400, department: 'Lower Limb X-Ray' },
  { id: 'test-XLL09', code: 'XLL09', name: 'X-Ray Tibia/Fibula LAT', mrp: 400, department: 'Lower Limb X-Ray' },
  { id: 'test-XLL10', code: 'XLL10', name: 'X-Ray Ankle AP', mrp: 400, department: 'Lower Limb X-Ray' },
  { id: 'test-XLL11', code: 'XLL11', name: 'X-Ray Ankle LAT', mrp: 400, department: 'Lower Limb X-Ray' },
  { id: 'test-XLL12', code: 'XLL12', name: 'X-Ray Ankle Oblique', mrp: 400, department: 'Lower Limb X-Ray' },
  { id: 'test-XLL13', code: 'XLL13', name: 'X-Ray Foot AP', mrp: 400, department: 'Lower Limb X-Ray' },
  { id: 'test-XLL14', code: 'XLL14', name: 'X-Ray Foot LAT', mrp: 400, department: 'Lower Limb X-Ray' },
  { id: 'test-XLL15', code: 'XLL15', name: 'X-Ray Foot Oblique', mrp: 400, department: 'Lower Limb X-Ray' },
  { id: 'test-XLL16', code: 'XLL16', name: 'X-Ray Calcaneum LAT', mrp: 400, department: 'Lower Limb X-Ray' },
  { id: 'test-XLL17', code: 'XLL17', name: 'X-Ray Calcaneum axial', mrp: 400, department: 'Lower Limb X-Ray' },
  // 10) Dental / Maxillofacial X-Ray
  { id: 'test-XDE01', code: 'XDE01', name: 'X-Ray OPG (Orthopantomogram)', mrp: 700, department: 'Dental / Maxillofacial X-Ray' },
  { id: 'test-XDE02', code: 'XDE02', name: 'X-Ray Cephalogram LAT', mrp: 700, department: 'Dental / Maxillofacial X-Ray' },
  { id: 'test-XDE03', code: 'XDE03', name: 'X-Ray TM Joint (open/close views)', mrp: 800, department: 'Dental / Maxillofacial X-Ray' },
  { id: 'test-XDE04', code: 'XDE04', name: 'X-Ray Mandible AP', mrp: 400, department: 'Dental / Maxillofacial X-Ray' },
  { id: 'test-XDE05', code: 'XDE05', name: 'X-Ray Mandible LAT', mrp: 400, department: 'Dental / Maxillofacial X-Ray' },
  { id: 'test-XDE06', code: 'XDE06', name: 'X-Ray Mandible oblique', mrp: 400, department: 'Dental / Maxillofacial X-Ray' },
  { id: 'test-XDE07', code: 'XDE07', name: 'X-Ray Maxilla view', mrp: 400, department: 'Dental / Maxillofacial X-Ray' },
  // 11) Contrast X-Ray
  { id: 'test-XCO01', code: 'XCO01', name: 'X-Ray Barium swallow', mrp: 2500, department: 'Contrast X-Ray' },
  { id: 'test-XCO02', code: 'XCO02', name: 'X-Ray Barium meal', mrp: 3000, department: 'Contrast X-Ray' },
  { id: 'test-XCO03', code: 'XCO03', name: 'X-Ray Barium follow-through', mrp: 3500, department: 'Contrast X-Ray' },
  { id: 'test-XCO04', code: 'XCO04', name: 'X-Ray Barium enema', mrp: 4000, department: 'Contrast X-Ray' },
  { id: 'test-XCO05', code: 'XCO05', name: 'X-Ray MCU (Micturating cystourethrogram)', mrp: 3000, department: 'Contrast X-Ray' },
  { id: 'test-XCO06', code: 'XCO06', name: 'X-Ray RGU (Retrograde urethrogram)', mrp: 3000, department: 'Contrast X-Ray' },
  { id: 'test-XCO07', code: 'XCO07', name: 'X-Ray IVP series / KUB series', mrp: 3500, department: 'Contrast X-Ray' },
  { id: 'test-XCO08', code: 'XCO08', name: 'X-Ray HSG (Hysterosalpingography)', mrp: 4000, department: 'Contrast X-Ray' },
  // 12) Special Orthopedic Views
  { id: 'test-XOR01', code: 'XOR01', name: 'X-Ray Scaphoid view', mrp: 400, department: 'Special Orthopedic Views' },
  { id: 'test-XOR02', code: 'XOR02', name: 'X-Ray Axial patella view', mrp: 400, department: 'Special Orthopedic Views' },
  { id: 'test-XOR03', code: 'XOR03', name: 'X-Ray Stress views', mrp: 800, department: 'Special Orthopedic Views' },
  { id: 'test-XOR04', code: 'XOR04', name: 'X-Ray Weight-bearing ankle', mrp: 400, department: 'Special Orthopedic Views' },
  { id: 'test-XOR05', code: 'XOR05', name: 'X-Ray Weight-bearing knee', mrp: 400, department: 'Special Orthopedic Views' },
  { id: 'test-XOR06', code: 'XOR06', name: 'X-Ray Tunnel view knee', mrp: 400, department: 'Special Orthopedic Views' },
  { id: 'test-XOR07', code: 'XOR07', name: 'X-Ray AP mortise ankle view', mrp: 400, department: 'Special Orthopedic Views' },
  // 13) Pediatric X-Ray
  { id: 'test-XPE01', code: 'XPE01', name: 'X-Ray Bone age', mrp: 400, department: 'Pediatric X-Ray' },
  { id: 'test-XPE02', code: 'XPE02', name: 'X-Ray Babygram', mrp: 1000, department: 'Pediatric X-Ray' },
  { id: 'test-XPE03', code: 'XPE03', name: 'X-Ray Neonatal chest', mrp: 400, department: 'Pediatric X-Ray' },
  { id: 'test-XPE04', code: 'XPE04', name: 'X-Ray Pediatric abdomen', mrp: 400, department: 'Pediatric X-Ray' },
  { id: 'test-XPE05', code: 'XPE05', name: 'X-Ray Long bone X-Ray', mrp: 400, department: 'Pediatric X-Ray' },
  { id: 'test-XPE06', code: 'XPE06', name: 'X-Ray Epiphyseal plate views', mrp: 400, department: 'Pediatric X-Ray' },
  // 14) Full-Length Studies
  { id: 'test-XFL01', code: 'XFL01', name: 'X-Ray Full spine AP', mrp: 1500, department: 'Full-Length Studies' },
  { id: 'test-XFL02', code: 'XFL02', name: 'X-Ray Full spine LAT', mrp: 1500, department: 'Full-Length Studies' },
  { id: 'test-XFL03', code: 'XFL03', name: 'X-Ray Full leg length / Scanogram', mrp: 1500, department: 'Full-Length Studies' },
];

export const mockSettings: Settings = {
    shopName: 'Smart Health Diagnostics',
    address: '123 Health St, Wellness City, 400001',
    phone: '+91 98765 43210',
    logoUrl: undefined,
    upiId: 'smarthealth@upi',
    gstin: '27ABCDE1234F1Z5',
    defaultPrintSize: 'A4',
};

export const mockEmployees: Employee[] = [];

export const mockSalaryPayments: SalaryPayment[] = [];

export const mockDailyExpenses: DailyExpense[] = [];

export const mockParties: Party[] = [];

export const mockPartyPayments: PartyPayment[] = [];

export const mockBills: Bill[] = [];

export const mockDues: Due[] = [];
